/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttijariRouteImport } from './routes/attijari'
import { Route as CihRouteImport } from './routes/cih'
import { Route as WafacashRouteImport } from './routes/wafacash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttijariRoute = AttijariRouteImport.update({
  id: '/attijari',
  path: '/attijari',
  getParentRoute: () => rootRouteImport,
} as any)
const CihRoute = CihRouteImport.update({
  id: '/cih',
  path: '/cih',
  getParentRoute: () => rootRouteImport,
} as any)
const WafacashRoute = WafacashRouteImport.update({
  id: '/wafacash',
  path: '/wafacash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attijari': typeof AttijariRoute
  '/cih': typeof CihRoute
  '/wafacash': typeof WafacashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attijari': typeof AttijariRoute
  '/cih': typeof CihRoute
  '/wafacash': typeof WafacashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attijari': typeof AttijariRoute
  '/cih': typeof CihRoute
  '/wafacash': typeof WafacashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attijari' | '/cih' | '/wafacash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attijari' | '/cih' | '/wafacash'
  id: '__root__' | '/' | '/attijari' | '/cih' | '/wafacash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttijariRoute: typeof AttijariRoute
  CihRoute: typeof CihRoute
  WafacashRoute: typeof WafacashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attijari': {
      id: '/attijari'
      path: '/attijari'
      fullPath: '/attijari'
      preLoaderRoute: typeof AttijariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cih': {
      id: '/cih'
      path: '/cih'
      fullPath: '/cih'
      preLoaderRoute: typeof CihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wafacash': {
      id: '/wafacash'
      path: '/wafacash'
      fullPath: '/wafacash'
      preLoaderRoute: typeof WafacashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttijariRoute: AttijariRoute,
  CihRoute: CihRoute,
  WafacashRoute: WafacashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
